### ISSUE TITLE
my issues, How do I solve this problem?

### ISSUE THREAD

**Issue by liuwd2333** [datorama/zabbix_rds_template#12]
item "xxxx:rds_stats.py["--metric","WriteThroughput","--instance-id","{HOST.HOST}","--access-key","{$AWS_ACCESS_KEY}","--secret-key","{$AWS_SECRET_KEY}","--region","{$REGION}"]" became not supported: Value "sh: 1: /usr/lib/zabbix/externalscripts/rds_stats.py: not found" of type "string" is not suitable for value type "Numeric (float)"

**Comment by sboyd67** [comment]
I know this has been around for a while but I'm having the same issue.  This is a great script.  But I'm getting an error when I try to run the script in zabbix (3.4)  Value "Traceback (most recent call last):
File "/etc/zabbix/externalscripts/srb_stats.py", line 5, in <module>
import boto3
File "/usr/lib/python2.7/site-packages/boto3/__init__.py", line 16, in <module>
from boto3.session import Session
File "/usr/lib/python2.7/site-packages/boto3/session.py", line 17, in <module>
import botocore.session
File "/usr/lib/python2.7/site-packages/botocore/session.py", line 29, in <module>
import botocore.configloader
File "/usr/lib/python2.7/site-packages/botocore/configloader.py", line 19, in <module>
from botocore.compat import six
File "/usr/lib/python2.7/site-packages/botocore/compat.py", line 26, in <module>
from urllib3 import exceptions
ImportError: No module named urllib3" of type "string" is not suitable for value type "Numeric (float)"

Not sure what to do because it works in the cli.  I have a modified version, where I pass the variables in the script (with the exception of the instance id) and it runs in the cli  but when I try to run it in zabbix I get the urllib3" of type "string" error
Any help is appreciated....

**Comment by astroluxe** [comment]
I had this issue. It went away when I installed boto3 using apt-get, rather than pip:
```
sudo apt-get install python-boto3
```

**Comment by jinupaulec** [comment]
Hope this helps some one.
on script file rds_stats.py
Shebang line #!/usr/bin/python is the issue.
we are running on ubuntu 20.04 and python3 was installed, so i had to make a symbolic link to python3 with below command.

sudo ln -s python3 /usr/bin/python

**Comment by yarons** [comment]
You can also set the shebang to #!/usr/bin/python3 instead :)

**Comment by jinupaulec** [comment]
also correct, need the systemwide change.
